unbind C-b
set -g prefix C-t
bind C-t send-prefix

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind s split-window -h

set -g status-style "fg=white,bg=black"
set -g mouse on
